/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoserBoardImport } from './routes/loser-board'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LoserBoardRoute = LoserBoardImport.update({
  id: '/loser-board',
  path: '/loser-board',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/loser-board': {
      id: '/loser-board'
      path: '/loser-board'
      fullPath: '/loser-board'
      preLoaderRoute: typeof LoserBoardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loser-board': typeof LoserBoardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loser-board': typeof LoserBoardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/loser-board': typeof LoserBoardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loser-board'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loser-board'
  id: '__root__' | '/' | '/loser-board'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoserBoardRoute: typeof LoserBoardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoserBoardRoute: LoserBoardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/loser-board"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/loser-board": {
      "filePath": "loser-board.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
